# Generated by Django 3.2.4 on 2021-09-20 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='type',
            field=models.CharField(choices=[('Driver', 'Driver'), ('Customer', 'Customer'), ('Consumer', 'Consumer')], max_length=20),
        ),
    ]
