# Generated by Django 3.2.4 on 2021-09-26 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0002_account_trade_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='phone',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='account',
            name='type',
            field=models.CharField(choices=[('Driver', 'Driver'), ('Customer', 'Customer'), ('Supplier', 'Supplier')], max_length=20),
        ),
    ]
