# Generated by Django 3.2.4 on 2021-09-11 20:38

from django.db import migrations
import location_field.models.plain


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0002_alter_place_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='location',
            field=location_field.models.plain.PlainLocationField(max_length=63),
        ),
    ]
