# Generated by Django 3.2.4 on 2021-09-26 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0002_auto_20210926_1555'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='iamge',
            new_name='image',
        ),
    ]
