# Generated by Django 3.2.4 on 2021-09-19 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0003_order_delivered'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat_lng', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
