# Generated by Django 3.2.4 on 2021-09-11 23:00

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0003_alter_place_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='point',
            field=django.contrib.gis.db.models.fields.PointField(null=True, srid=4326),
        ),
    ]
