# Generated by Django 3.2.4 on 2021-09-19 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0004_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='lat_lng',
            field=models.CharField(max_length=100),
        ),
    ]
