# Generated by Django 3.2.4 on 2021-09-12 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0005_rename_city_place_lat_lng'),
    ]

    operations = [
        migrations.RenameField(
            model_name='place',
            old_name='location',
            new_name='address',
        ),
        migrations.AlterField(
            model_name='place',
            name='lat_lng',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
