# Generated by Django 3.2.4 on 2021-09-21 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0006_auto_20210920_1229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='lat_lng',
            field=models.CharField(max_length=100),
        ),
        migrations.RemoveField(
            model_name='order',
            name='shop',
        ),
        migrations.AddField(
            model_name='order',
            name='shop',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tracking.shop'),
        ),
    ]
