# Generated by Django 3.2.4 on 2021-09-12 01:40

from django.db import migrations, models
import location_field.models.plain


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0007_auto_20210912_0315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='lat_lng',
            field=location_field.models.plain.PlainLocationField(max_length=63),
        ),
    ]
