# Generated by Django 3.2.4 on 2021-09-21 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0007_auto_20210921_1811'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='search',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.CharField(max_length=255),
        ),
    ]
