# Generated by Django 3.2.4 on 2021-09-21 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0008_auto_20210921_1819'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='search',
            new_name='place',
        ),
    ]
