# Generated by Django 3.2.4 on 2021-09-12 01:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0009_auto_20210912_0345'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='point',
        ),
    ]
