# Generated by Django 3.2.4 on 2021-09-21 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0010_alter_order_shop'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Driver',
        ),
    ]
