# Generated by Django 3.2.4 on 2021-09-12 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0012_auto_20210912_0401'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='ordered',
        ),
        migrations.AddField(
            model_name='order',
            name='ordered',
            field=models.BooleanField(default=False),
        ),
    ]
