# Generated by Django 3.2.4 on 2021-09-12 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0013_auto_20210912_1312'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='my_address',
        ),
    ]
