# Generated by Django 3.2.4 on 2021-09-12 16:37

from django.db import migrations
import location_field.models.plain


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0014_remove_driver_my_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='my_location',
            field=location_field.models.plain.PlainLocationField(max_length=63),
        ),
    ]
